name : Audit

on :
    push :
        branches : [main]
    pull_request :
        branches : [main]

jobs :
    audit :
        runs-on : ubuntu-20.04
        steps :
        - uses : actions/checkout@v2

        - name : set up golang rest api
          uses : actions/setup-go@v2
          with :
            go-version: 1.21.5

        - name : Verify Dependencies of the project
          uses : go mod verify

        - name : Install lint checker
          uses : go install golang.org/x/lint/golint@latest

        - name : Run golint
          uses : golint ./..

        - name :  Build
          uses : go build -v ./..


